services:
  nv-ssh:
    build: .  # Assuming your Dockerfile is in the same directory as docker-compose.yml
    image: nv-ssh
    container_name: nv-ssh
    ports:
      - "5566:22"
    volumes:
      - ./.vscode-server/:/home/ubuntu/.vscode-server/
      - ./.ssh/:/home/ubuntu/.ssh/:ro  # Ensure this directory exists and has authorized_keys
    working_dir: /home/ubuntu/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash"]