services:
  nv-ssh:
    build: .  # Assuming your Dockerfile is in the same directory as docker-compose.yml
    image: nv-ssh
    container_name: nv-ssh
    ports:
      - "5566:22"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: ["/bin/bash", "-c", "service ssh start && /bin/bash"]