apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-ssh-pod
spec:
  containers:
    - name: ubuntu-ssh-container
      image: ubuntu-ssh:latest
      workingDir: /home/ubuntu/app
      ports:
        - containerPort: 22
          hostPort: 5679
      volumeMounts:
        - name: ssh-volume
          mountPath: /home/ubuntu/.ssh/
      securityContext:
        capabilities:
          add: ["CAP_SYS_ADMIN"]
      tty: true
      stdin: true
  volumes:
    - name: ssh-volume
      hostPath:
        path: ./.ssh/
        type: Directory
  restartPolicy: Never
  hostNetwork: false